version: "3.7"
services:
  spark-master:
    image: spark-master:latest
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./result:/opt/spark-result
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: spark-worker:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=512m
      - SPARK_EXECUTOR_MEMORY=1024m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - ./result:/opt/spark-result
